name: Ejecutar Script Diario

on:
  schedule:
    - cron: '0 6 * * *'   # 7:00 hora Madrid (invierno)
    - cron: '0 13 * * *'  # 14:00 hora Madrid (invierno)
    - cron: '0 19 * * *'  # 20:00 hora Madrid (invierno)
  workflow_dispatch:     

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt"

      - name: Ejecutar el script
        run: |
          app.py
