name: Ejecutar Script Diario

on:
  schedule:
    - cron: '0 5 * * *'   # 7:00 hora Madrid (verano)
    - cron: '0 12 * * *'  # 14:00 hora Madrid (verano)
    - cron: '0 18 * * *'  # 20:00 hora Madrid (verano)
  workflow_dispatch:

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          USUARIO: ${{ secrets.USUARIO }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DIRECCION_REMITENTE: ${{ secrets.DIRECCION_REMITENTE }}
          PASS_REMITENTE: ${{ secrets.PASS_REMITENTE }}
          DIRECCION_DESTINATARIO: ${{ secrets.DIRECCION_DESTINATARIO }}
          TOKEN: ${{ secrets.TOKEN }}
        run: python app.py

